### ISSUE TITLE
GetMRef

### ISSUE THREAD

**Issue by LolitaZT** [vtex-soft/texsupport.ims-ejpecp#1]
This repo contains an old version of GetMRef which is less accurate and flexible:
https://github.com/vtex-soft/texsupport.ims-ejpecp/blob/master/mgetmref.py
It would be advisable to redirect EJPECP authors to the latest GetMRef version:
https://github.com/vtex-soft/getmref

**Comment by dgalcius** [comment]
OK. Do you consider uploading the script to CTAN? The script would end up into TeXLive distro, so I could remove the old version form the package.

**Comment by edgaras-sakuras** [comment]
The newest version of getmref added. CTAN and other issues will be added on script repo.
