### ISSUE TITLE
Preprint option to omit journal logos and references

### ISSUE THREAD

**Issue by neldredge** [vtex-soft/texsupport.ims-ejpecp#2]
It would be a nice feature for this class if besides the `EJP` and `ECP` options, there was a third option (e.g. `PREPRINT`) which just formatted the article without the journal's name, logo or publication data.

As an author, when my paper is accepted, I would like to update the preprint on arXiv, my personal website, etc, with the final peer-reviewed text.  It is sort of tacky to use ejpecp when doing this, since it doesn't feel proper to include the journal's name and logo on a file that is not the "official" version.  It also includes a bunch of placeholders for paper number, DOI, etc, that look bad.  

But the alternative is to maintain a separate version of the file using some other document class (`article`, `amsart`, etc).  There may be nontrivial differences to conform to their different handling of metadata, environments, etc, and it is a pain to keep them in sync.

It would be great if I could have just one source file, and set `PREPRINT` when uploading elsewhere.

**Comment by edgaras-sakuras** [comment]
Hello,

Thank You for the decent explanation!

I've added it but in slightly different way:

```LaTeX
\documentclass[ECP,preprint]{ejpecp}
```

or

```LaTeX
\documentclass[EJP,preprint]{ejpecp}
```

One needs to know a height of the journal information logo in a first page to keep layout the same.
